In [1]:
import numpy as np

#одномерный массив
a = np.array([1, 2, 3, 4, 5, 6, 8, 9 ])
print(a,a.shape,a.dtype)

#нулевой массив
a1 = np.zeros((3, 3))
print(a1)

#масис от 0-9
a2 = np.arange(10)
print(a2)


#первый эл массива
a3 = a[0]
print(a3)

#тоже самое что выше ток двухмер
a4 = np.array([[10, 20, 30],
               [40, 50, 60],
               [70, 80, 90]])
a5 = a4[1, 2]
print(a5)

#сумма чисел из массива
summ = np.sum(a)
print(summ)

#сред знач двухмер массива
a6 = np.mean(a4)
print(a6)

#каждое число в массиве умножаем на 2
a7 = a * 2 
print(a7)

[1 2 3 4 5 6 8 9] (8,) int64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0 1 2 3 4 5 6 7 8 9]
1
60
38
50.0
[ 2  4  6  8 10 12 16 18]
